version: "3"

services:
  stellar:
    image: stellar/quickstart:soroban-dev@sha256:8a99332f834ca82e3ac1418143736af59b5288e792d1c4278d6c547c6ed8da3b
    container_name: soroban-network
    command: ["--standalone", "--enable-soroban-rpc"]
    ports:
      - '8000:8000'