name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v3

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build clear-contract-deployer
        run: cargo build --target wasm32-unknown-unknown --release -p clear-contract-deployer

      - name: Build clear-contract
        run: cargo build --target wasm32-unknown-unknown --release -p clear-contract
  
      - name: Run tests
        run: cargo test --verbose