name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup target add wasm32-unknown-unknown

      - name: Build liquidity-pool
        run: cargo build --target wasm32-unknown-unknown --release -p liquidity-pool

      - name: Build liquidity-pool-deployer
        run: cargo build --target wasm32-unknown-unknown --release -p liquidity-pool-deployer
  
      - name: Run tests
        run: cargo test --verbose